# Generated by Django 4.2.2 on 2023-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=30)),
                ('descripción', models.CharField(max_length=200)),
                ('vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENPROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada')], max_length=11)),
                ('categoría', models.CharField(choices=[('TRABAJO', 'Trabajo'), ('HOGAR', 'Hogar'), ('ESTUDIO', 'Estudio')], max_length=7)),
            ],
        ),
    ]
