# Generated by Django 4.2.2 on 2023-06-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0002_tarea_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='vencimiento',
        ),
    ]
