# Generated by Django 4.2.2 on 2023-07-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0006_prioridad_tarea_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridad',
            name='nombre',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Baja', max_length=5, null=True),
        ),
    ]
