# Generated by Django 4.0.10 on 2023-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=70)),
                ('género', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=15)),
                ('dirección', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=60)),
                ('contraseña', models.CharField(max_length=32)),
                ('cargo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('vigencia', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=70)),
                ('género', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=15)),
                ('dirección', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=60)),
                ('previsión', models.CharField(max_length=20)),
                ('convenio', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
