# Generated by Django 4.0.10 on 2023-06-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rut',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
